echo "-----------------------------------"
echo "Tugas 1 SISOP Kelas-B"
echo "-----------------------------------"
echo "Nama : Rizal Harjo Utomo"
echo "NPM  : 210831010101"
echo "-----------------------------------"
echo "notes:"
echo "-----------------------------------"
echo -e "hallo dunia!\nIni adalah skrip Bash pertamaku di Linux"
